# Generated by Django 3.2 on 2024-12-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.IntegerField(default=10000, verbose_name='Код подтверждения'),
            preserve_default=False,
        ),
    ]
