# Generated by Django 3.2 on 2024-12-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_yamdbuser_confirmation_code'),
        ('users', '0003_alter_yamdbuser_username'),
    ]

    operations = [
    ]
