# Generated by Django 3.2 on 2024-12-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20241224_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(max_length=5, verbose_name='Код подтверждения'),
        ),
    ]
