# Generated by Django 3.2 on 2024-12-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_yamdbuser_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='confirmation_code',
        ),
    ]
